# This notebook looks over the data we will be using and it's preprocessing

### We are using yahoo finance lib

---

1. Downloading Market Data

In [1]:
import yfinance as yf

df = yf.download(
    "AAPL",
    start="2020-01-01",
    end="2025-01-01",
    interval="1d"
)

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.333885  72.394093  71.091191  71.344062  135480400
2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800
2020-01-06  72.201416  72.239950  70.503554  70.754021  118387200
2020-01-07  71.861847  72.466330  71.642689  72.211049  108872000
2020-01-08  73.017838  73.318877  71.565621  71.565621  132079200

In [2]:
df.head()

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.333885  72.394093  71.091191  71.344062  135480400
2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800
2020-01-06  72.201416  72.239950  70.503554  70.754021  118387200
2020-01-07  71.861847  72.466330  71.642689  72.211049  108872000
2020-01-08  73.017838  73.318877  71.565621  71.565621  132079200

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1258 entries, 2020-01-02 to 2024-12-31
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   1258 non-null   float64
 1   (High, AAPL)    1258 non-null   float64
 2   (Low, AAPL)     1258 non-null   float64
 3   (Open, AAPL)    1258 non-null   float64
 4   (Volume, AAPL)  1258 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 59.0 KB

In [8]:
df.shape

(1258, 5)

In [9]:
df.isna().sum()

Price   Ticker
Close   AAPL      0
High    AAPL      0
Low     AAPL      0
Open    AAPL      0
Volume  AAPL      0
dtype: int64

In [4]:

df.describe()

Price         Close         High          Low         Open        Volume
Ticker         AAPL         AAPL         AAPL         AAPL          AAPL
count   1258.000000  1258.000000  1258.000000  1258.000000  1.258000e+03
mean     151.377786   152.899566   149.680871   151.223470  9.057103e+07
std       41.851999    41.992363    41.629303    41.795805  5.324438e+07
min       54.163700    55.160698    51.324796    55.059309  2.323470e+07
25%      126.279127   127.397089   124.278517   125.724387  5.546825e+07
50%      149.968590   151.709757   148.037172   149.788874  7.628335e+07
75%      175.902035   177.452441   174.337264   175.708242  1.077425e+08
max      257.375610   258.448771   255.994450   256.550893  4.265100e+08

---

#### Conclusion: 
Data is clean Let's move to feature Engg. to use the given data into useable features for our model

---

loading df to csv for further process

In [10]:
import os

os.makedirs("../data", exist_ok=True)

df.to_csv(
    "../data/btc_usd_daily.csv",
    index=True
)

print("Saved successfully!")

Saved successfully!